### PR TITLE
Add mib.Node.typeName and mib.getByOid

### PR DESCRIPTION
**Pull request by Daemonae**
I'm wondering if you think type's setter and deleter should be moved to typeName to provide cleaner semantics.

### CODE REVIEW

**Comment by vincentbernat** [comment]
Yes, it would be cleaner to set the setter for `typeName` instead of `type`. Can you add a commit for that?

**Comment by vincentbernat** [comment]
Sorry, I pushed some other changes meanwhile, so your PR cannot be merged anymore. The adaptation should be easy, some of the stuff has just been moved to `smi.py` instead of `mib.py`.

**Comment by Daemonae** [comment]
No problem. I've rebased and fixed up these and my other in-progress changes.

**Comment by vincentbernat** [comment]
So, it's ready to be merged, right?

**Comment by Daemonae** [comment]
Yup!

**Comment by vincentbernat** [comment]
Thanks!

**Pull request merged**
