### PR TITLE
Permit adding new search paths

### PR DESCRIPTION
**Pull request by rarylson**
When using snimpy, sometimes we want to load a MIB that isn't in the default libsmi path.

Currently, there are two modes to load this MIB:

- Using the MIB full path;
    - It is useful when the MIB is located in a well-know directory. So, if we have many MIB directories, it's dificult to locate this MIB at execution time;
    - We could implement a search function, but it's already implemented in the libsmi (snimpy uses this functionality in the manager.load function).
- Using a global/user libsmi config file (using the 'snimpy' tag, that is used in the smiInit function - mib module);
    - It works in most systems, but the user must learn how to config libsmi;
    - In my HomeBrew install, libsmi doesn't automatically read any global config file. To use a config file, we would need that the smiReadConfig function was exposed (but it isn't).

So, I propose that snimpy implement the `set_path` function (in the MIB module) to permit the user to add search paths before loading modules.

**PS:** May be interesting, in a future, to implement a `read_path` function, or to make `set_path` to return the new path.

### CODE REVIEW

**Comment by vincentbernat** [comment]
Hi!

Thanks for the PR!

Could you amend your latest commit by fixing the lint issue (you can use `make lint`). Otherwise, I'll do it myself.

**Comment by rarylson** [comment]
Hi, thanks for the warning.

Now, I think the code is PEP8 complient.

**Comment by vincentbernat** [comment]
Could you also squash your commits into a single one? Again, I can also do it myself if you don't know how.

**Comment by rarylson** [comment]
Hi,

I rebase the forked repo. There is only a single commit now.

**Comment by vincentbernat** [comment]
Thanks! I have updated your commit here to allow one to get the path too: 740dd50d04dd

**Comment by rarylson** [comment]
Hi,

Thanks for accepting the pull request and for improving the code.

**Pull request merged**
