### PR TITLE
Simple support for Notification MIB nodes

### PR DESCRIPTION
**Pull request by iwanb**
To support #72 I would like to get MIB information about notfications, so I can get the notification name (from an OID) and check the object list. To do e.g.:

`
notification = mib.getFromOid(manager.nlmLogNotificationID[idx])
assert str(notification) == "myNotification"
allowed = [] # allowed varbind names
for object in notification.objects:
     allowed.append(str(object))
`

It can also be useful for devices implementing the NOTIFICATION-LOG-MIB

### CODE REVIEW

**Comment by vincentbernat** [comment]
The failures seem to be related to an infrastructure change on Travis. I'll try to fix that shortly. Otherwise, your code seems good. Thanks!

**Comment by iwanb** [comment]
After trying it a bit more, it seems a notification can hold any object identifier, so to have notification.objects work in all cases I would have to add support for other "node kinds" to the SMI wrapper.

**Comment by vincentbernat** [comment]
Could you rebase your PR on master? I have fixed tests.

**Comment by vincentbernat** [comment]
I have merged it manually (GitHub seemed a bit confused about the content, showing a lot of diff). Thanks!

**Comment by iwanb** [comment]
Great, thanks!

**Pull request closed without merging**
